sudo: false
language: python
python:
  - "3.11"
  - "pypy"
install: ":"
script: ./test-everything.sh

notifications:
  email:
    on_success: changed
    on_failure: always
  irc:
    channels:   "libera.chat#themanaworld-irc"
    on_success: always
    on_failure: always
    use_notice: true
